heat_template_version: 2013-05-23

description: >
  HOT template that invokes subtemplates
parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image_ubnt20:
    type: string
    description: Name of image to use for servers
    default: Ubuntu Server 20.04 LTS (Focal Fossa) amd64
  image_ubnt18:
    type: string
    description: Name of image to use for servers
    default: Ubuntu Server 18.04 LTS (Bionic Beaver) amd64
  image_kali19:
    type: string
    description: Name of image to use for servers
    default: Kali Linux 2019.4 xfce amd64 
  image_kali20:
    type: string
    description: Name of image to use for servers
    default: Kali Linux 2020.3 xfce amd64
  sec_group_linux:
    type: comma_delimited_list
    description: Security groups
    default: default,linux
  sec_group_windows:
    type: comma_delimited_list
    description: Security groups
    default: default,windows
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: ntnu-internal
 
resources:

  base:
    type: base.yaml
    properties:
      key_name:          { get_param: key_name }
      image_kali19:       { get_param: image_kali19 }
      image_kali20:       { get_param: image_kali20 }
      image_ubnt18:       { get_param: image_ubnt18 }
      image_ubnt20:       { get_param: image_ubnt20 }
      public_net:        { get_param: public_net }  
      sec_group_linux:   { get_param: sec_group_linux }  

  rest:
    type: rest.yaml
    depends_on: base
    properties:
      key_name:          { get_param: key_name }
      image_kali19:       { get_param: image_kali19 }
      image_kali20:       { get_param: image_kali20 }
      image_ubnt18:       { get_param: image_ubnt18 }
      image_ubnt20:       { get_param: image_ubnt20 }
      sec_group_linux:   { get_param: sec_group_linux }  
      sec_group_windows: { get_param: sec_group_windows }
      public_net:        { get_param: public_net }  
      admin_net:         { get_attr: [base,admin_net] }
      admin_subnet:      { get_attr: [base,admin_subnet] }
      manager_ip:        { get_attr: [base,manager_ip] }

outputs:
  manager_ip:
    description: IP address of manager in the admin network
    value: { get_attr: [iac_base,manager_ip] }
